Adding bugs, various script updates and additions

diff --git a/mariadb-build-qa/kill_all b/mariadb-build-qa/kill_all
--- a/mariadb-build-qa/kill_all
+++ b/mariadb-build-qa/kill_all
@@ -3,9 +3,21 @@
 
 # The ./kill script ensures the correct PID is selected (via random PORT= assignment)
 
+GENDIRS=gendirs.sh
+if [ ! -r ./${GENDIRS} ]; then 
+  if [ -r ../${GENDIRS} ]; then
+    GENDIRS=../gendirs.sh
+  else
+    echo "./gendirs.sh not found!"
+    exit 1
+  fi
+else 
+  GENDIRS=./gendirs.sh 
+fi
+
 ASAN=""
 if [ "${1}" == "ASAN" ]; then ASAN="ASAN"; fi
 set +H
-./gendirs.sh ${ASAN} | xargs -I{} echo "cd {}; if [ -r ./kill ]; then ./kill; else echo './kill did not exist for directory {} - please run ./startup_all or instead do cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} sh -c "{}"
+${GENDIRS} ${ASAN} | xargs -I{} echo "cd {}; if [ -r ./kill ]; then ./kill; else echo './kill did not exist for directory {} - please run ./startup_all or instead do cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} sh -c "{}"
 
 sync
