Script updates

diff --git a/homedir_scripts/gomd b/homedir_scripts/gomd
--- a/homedir_scripts/gomd
+++ b/homedir_scripts/gomd
@@ -15,6 +15,8 @@ TOTALRUNS=$[ ${RUNSOPT} + ${RUNSDBG} ]
 for RUN in $(seq 1 ${TOTALRUNS}); do
   rm -f /tmp/gomd_helper
   cd ~/mariadb-qa
+  if [[ "${CONF}" == *"/"* ]]; then echo "Assert: no paths/directories allowed in CONF (${CONF}) setting!"; exit 1; fi
+  if [ ! -r ${CONF} ]; then echo "Assert: ${CONF} not found!"; exit 1; fi
   sed -i "s|^BASEDIR=\([^#]\+\)|BASEDIR=${BASEDIR}   |" ${CONF}
   if [ ${RUN} -le ${RUNSOPT} ]; then  # Opt runs
     sed -i 's|^BASEDIR=\([^#]\+\)-dbg|BASEDIR=\1-opt|' ${CONF}
